services:
  flask_app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    networks:
      - app_network
      
  flask_db:
    image: postgres
    ports:  
      # host_port:container_port
      - "5432:5432"
    environment:
      -   POSTGRES_USER=postgres
      -   POSTGRES_PASSWORD=postgres
      -   POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - flask_db
    volumes:
      - adminer_data:/var/www/html
    networks:
      - adminer_network

networks:
  adminer_network:
    name: adminer_network
    driver: bridge
  app_network:
    name: app_network
    driver: bridge
  

volumes:
  pgdata: {}
  adminer_data: {}


